
cc_binary(
    name = "greeter_client",
    srcs = ["greeter_client.cc"],
    deps = [
        "//helloworld/HelloWorldGRPC:helloworld_cc_grpc",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
    ],
)
