load("@rules_proto_grpc//cpp:defs.bzl", "cpp_grpc_library")

package(default_visibility = ["//visibility:public"])

cpp_grpc_library(
    name = "helloworld_cc_grpc",
    protos = ["//helloworld/protos:helloworld_proto"],
)
